name: Build Linux App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pillow

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --clean --onefile f4_main.py --paths . --hidden-import=pyinstaller_import


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/f4_main
